defaults:
  - model: small
  - _self_

n_prev: 8
n_next: 12
tf: 100 #full teacher forcing by default
optimizer: "adam"

size: 224
scene: "bookstore"
video: 0
box_size: 0

seed: 1
device: 0
pos: False
img: False
multi_cam: []

save_run: True
verbose: False



