defaults:
  - model: small
  - _self_

n_prev: 8
n_next: 12
tf: 100 #full teacher forcing by default
optimizer: "adam"

size: 224
scene: "bookstore"
video: 0
box_size: 0
img_step: 12 # 2.5 fps for the 8-12 protocol

seed: 1
device: 0
pos: False
img: False
multi_cam: []

save_run: True
verbose: False  # for displaying printing info

data_path: "/waldo/walban/student_datasets/arfranck/SDD/scenes/"
saving_path: "/linux/grotsartdehe/"




