params:
  batch_size: 16
  dropout: 0.1
  learning_rate: 5e-5
  layer: 6
  embedding_size: 256
  neuron: 64
  output_size: 64
  nbrSerie: 100
  nbrImages: 16
  lengthSerie: 130
  regularity: "Regular"
